theme: jekyll-theme-cayman
title: Study-ext
description: Study application that lets you set up study sessions at UH
github:
  is_project_page: true
  repository_url: https://github.com/Study-ext/study-ext.github.io
